[2021-02-05T20:15:02.047097+01:00] php.DEBUG: Warning: filemtime(): stat failed for C:\Users\Austin\Desktop\G3Excercise\G3Exercise\config\routes\dev\framework.yaml {"exception":{"Symfony\\Component\\ErrorHandler\\Exception\\SilencedErrorContext":{"severity":2,"file":"C:\\Users\\Austin\\Desktop\\G3Excercise\\vendor\\symfony\\config\\Resource\\FileResource.php","line":65,"trace":[{"file":"C:\\Users\\Austin\\Desktop\\G3Excercise\\vendor\\symfony\\config\\Resource\\SelfCheckingResourceChecker.php","line":34,"function":"isFresh","class":"Symfony\\Component\\Config\\Resource\\FileResource","type":"->"}],"count":1}}} []
[2021-02-05T20:15:04.051081+01:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /"" at C:\Users\Austin\Desktop\G3Excercise\vendor\symfony\http-kernel\EventListener\RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" at C:\\Users\\Austin\\Desktop\\G3Excercise\\vendor\\symfony\\http-kernel\\EventListener\\RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at C:\\Users\\Austin\\Desktop\\G3Excercise\\vendor\\symfony\\routing\\Matcher\\Dumper\\CompiledUrlMatcherTrait.php:182)"} []
[2021-02-05T20:15:04.913329+01:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"9cce67"},"request_uri":"http://localhost:8000/_wdt/9cce67","method":"GET"} []
[2021-02-05T20:15:06.816229+01:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /favicon.ico" (from "http://localhost:8000/")" at C:\Users\Austin\Desktop\G3Excercise\vendor\symfony\http-kernel\EventListener\RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /favicon.ico\" (from \"http://localhost:8000/\") at C:\\Users\\Austin\\Desktop\\G3Excercise\\vendor\\symfony\\http-kernel\\EventListener\\RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico/\". at C:\\Users\\Austin\\Desktop\\G3Excercise\\vendor\\symfony\\routing\\Matcher\\Dumper\\CompiledUrlMatcherTrait.php:70)"} []
[2021-02-05T20:18:12.701046+01:00] console.CRITICAL: Error thrown while running command "doctrine:database:create". Message: "An exception occurred in driver: could not find driver" {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in driver: could not find driver at C:\\Users\\Austin\\Desktop\\G3Excercise\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractPostgreSQLDriver.php:102)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at C:\\Users\\Austin\\Desktop\\G3Excercise\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDO\\Exception.php:18)\n[previous exception] [object] (PDOException(code: 0): could not find driver at C:\\Users\\Austin\\Desktop\\G3Excercise\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:38)","command":"doctrine:database:create","message":"An exception occurred in driver: could not find driver"} []
[2021-02-05T20:18:12.703367+01:00] console.DEBUG: Command "doctrine:database:create" exited with code "1" {"command":"doctrine:database:create","code":1} []
[2021-02-05T20:31:01.473597+01:00] request.INFO: Matched route "homepage". {"route":"homepage","route_parameters":{"_route":"homepage","_controller":"App\\Controller\\LuckyController::number"},"request_uri":"http://localhost:8000/","method":"GET"} []
[2021-02-05T20:31:01.491278+01:00] request.CRITICAL: Uncaught PHP Exception InvalidArgumentException: "The controller for URI "/" is not callable: Controller "App\Controller\LuckyController" does neither exist as service nor as class." at C:\Users\Austin\Desktop\G3Excercise\vendor\symfony\http-kernel\Controller\ControllerResolver.php line 88 {"exception":"[object] (InvalidArgumentException(code: 0): The controller for URI \"/\" is not callable: Controller \"App\\Controller\\LuckyController\" does neither exist as service nor as class. at C:\\Users\\Austin\\Desktop\\G3Excercise\\vendor\\symfony\\http-kernel\\Controller\\ControllerResolver.php:88)\n[previous exception] [object] (InvalidArgumentException(code: 0): Controller \"App\\Controller\\LuckyController\" does neither exist as service nor as class. at C:\\Users\\Austin\\Desktop\\G3Excercise\\vendor\\symfony\\http-kernel\\Controller\\ContainerControllerResolver.php:67)\n[previous exception] [object] (Error(code: 0): Class 'App\\Controller\\LuckyController' not found at C:\\Users\\Austin\\Desktop\\G3Excercise\\vendor\\symfony\\http-kernel\\Controller\\ControllerResolver.php:147)"} []
[2021-02-05T20:31:01.581302+01:00] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2021-02-05T20:31:02.015319+01:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"ce79d0"},"request_uri":"http://localhost:8000/_wdt/ce79d0","method":"GET"} []
[2021-02-05T20:33:30.891816+01:00] request.INFO: Matched route "homepage". {"route":"homepage","route_parameters":{"_route":"homepage","_controller":"App\\Controller\\DefaultController::number"},"request_uri":"http://localhost:8000/","method":"GET"} []
[2021-02-05T20:33:30.934297+01:00] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2021-02-05T20:33:31.407735+01:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"86d3d6"},"request_uri":"http://localhost:8000/_wdt/86d3d6","method":"GET"} []
[2021-02-05T20:33:32.533845+01:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /favicon.ico" (from "http://localhost:8000/")" at C:\Users\Austin\Desktop\G3Excercise\vendor\symfony\http-kernel\EventListener\RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /favicon.ico\" (from \"http://localhost:8000/\") at C:\\Users\\Austin\\Desktop\\G3Excercise\\vendor\\symfony\\http-kernel\\EventListener\\RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico/\". at C:\\Users\\Austin\\Desktop\\G3Excercise\\vendor\\symfony\\routing\\Matcher\\Dumper\\CompiledUrlMatcherTrait.php:70)"} []
[2021-02-05T20:34:02.645769+01:00] request.INFO: Matched route "homepage". {"route":"homepage","route_parameters":{"_route":"homepage","_controller":"App\\Controller\\DefaultController::index"},"request_uri":"http://localhost:8000/","method":"GET"} []
[2021-02-05T20:34:02.665703+01:00] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2021-02-05T20:34:03.094506+01:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"92a732"},"request_uri":"http://localhost:8000/_wdt/92a732","method":"GET"} []
[2021-02-05T20:34:04.182079+01:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /favicon.ico" (from "http://localhost:8000/")" at C:\Users\Austin\Desktop\G3Excercise\vendor\symfony\http-kernel\EventListener\RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /favicon.ico\" (from \"http://localhost:8000/\") at C:\\Users\\Austin\\Desktop\\G3Excercise\\vendor\\symfony\\http-kernel\\EventListener\\RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico/\". at C:\\Users\\Austin\\Desktop\\G3Excercise\\vendor\\symfony\\routing\\Matcher\\Dumper\\CompiledUrlMatcherTrait.php:70)"} []
[2021-02-05T20:39:40.853896+01:00] request.INFO: Matched route "homepage". {"route":"homepage","route_parameters":{"_route":"homepage","_controller":"App\\Controller\\DefaultController::index"},"request_uri":"http://localhost:8000/","method":"GET"} []
[2021-02-05T20:39:40.877132+01:00] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2021-02-05T20:39:41.320507+01:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"d69337"},"request_uri":"http://localhost:8000/_wdt/d69337","method":"GET"} []
[2021-02-05T20:39:42.405339+01:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /favicon.ico" (from "http://localhost:8000/")" at C:\Users\Austin\Desktop\G3Excercise\vendor\symfony\http-kernel\EventListener\RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /favicon.ico\" (from \"http://localhost:8000/\") at C:\\Users\\Austin\\Desktop\\G3Excercise\\vendor\\symfony\\http-kernel\\EventListener\\RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico/\". at C:\\Users\\Austin\\Desktop\\G3Excercise\\vendor\\symfony\\routing\\Matcher\\Dumper\\CompiledUrlMatcherTrait.php:70)"} []
[2021-02-05T20:42:25.605325+01:00] request.INFO: Matched route "homepage". {"route":"homepage","route_parameters":{"_route":"homepage","_controller":"App\\Controller\\DefaultController::index"},"request_uri":"http://localhost:8000/","method":"GET"} []
[2021-02-05T20:42:25.663768+01:00] request.CRITICAL: Uncaught PHP Exception Twig\Error\SyntaxError: "Arguments must be separated by a comma. Unexpected token "operator" of value "=" ("punctuation" expected with value ",")." at C:\Users\Austin\Desktop\G3Excercise\templates\login.html.twig line 13 {"exception":"[object] (Twig\\Error\\SyntaxError(code: 0): Arguments must be separated by a comma. Unexpected token \"operator\" of value \"=\" (\"punctuation\" expected with value \",\"). at C:\\Users\\Austin\\Desktop\\G3Excercise\\templates\\login.html.twig:13)"} []
[2021-02-05T20:42:25.779658+01:00] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2021-02-05T20:42:26.243535+01:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"d558cb"},"request_uri":"http://localhost:8000/_wdt/d558cb","method":"GET"} []
[2021-02-05T20:48:06.697410+01:00] console.CRITICAL: Error thrown while running command "make:auth". Message: "The autoloader expected class "App\Entity\User" to be defined in file "C:\Users\Austin\Desktop\G3Excercise\vendor\composer/../../src\Entity\User.php". The file was found but the class was not in it, the class name or namespace probably has a typo." {"exception":"[object] (RuntimeException(code: 0): The autoloader expected class \"App\\Entity\\User\" to be defined in file \"C:\\Users\\Austin\\Desktop\\G3Excercise\\vendor\\composer/../../src\\Entity\\User.php\". The file was found but the class was not in it, the class name or namespace probably has a typo. at C:\\Users\\Austin\\Desktop\\G3Excercise\\vendor\\symfony\\error-handler\\DebugClassLoader.php:400)","command":"make:auth","message":"The autoloader expected class \"App\\Entity\\User\" to be defined in file \"C:\\Users\\Austin\\Desktop\\G3Excercise\\vendor\\composer/../../src\\Entity\\User.php\". The file was found but the class was not in it, the class name or namespace probably has a typo."} []
[2021-02-05T20:48:06.699215+01:00] console.DEBUG: Command "make:auth" exited with code "1" {"command":"make:auth","code":1} []
[2021-02-05T20:48:37.232402+01:00] console.CRITICAL: Error thrown while running command "make:auth". Message: "The autoloader expected class "App\Entity\User" to be defined in file "C:\Users\Austin\Desktop\G3Excercise\vendor\composer/../../src\Entity\User.php". The file was found but the class was not in it, the class name or namespace probably has a typo." {"exception":"[object] (RuntimeException(code: 0): The autoloader expected class \"App\\Entity\\User\" to be defined in file \"C:\\Users\\Austin\\Desktop\\G3Excercise\\vendor\\composer/../../src\\Entity\\User.php\". The file was found but the class was not in it, the class name or namespace probably has a typo. at C:\\Users\\Austin\\Desktop\\G3Excercise\\vendor\\symfony\\error-handler\\DebugClassLoader.php:400)","command":"make:auth","message":"The autoloader expected class \"App\\Entity\\User\" to be defined in file \"C:\\Users\\Austin\\Desktop\\G3Excercise\\vendor\\composer/../../src\\Entity\\User.php\". The file was found but the class was not in it, the class name or namespace probably has a typo."} []
[2021-02-05T20:48:37.234568+01:00] console.DEBUG: Command "make:auth" exited with code "1" {"command":"make:auth","code":1} []
[2021-02-05T20:53:17.127594+01:00] request.INFO: Matched route "homepage". {"route":"homepage","route_parameters":{"_route":"homepage","_controller":"App\\Controller\\DefaultController::index"},"request_uri":"http://localhost:8000/","method":"GET"} []
[2021-02-05T20:53:17.135777+01:00] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"main","authenticators":1} []
[2021-02-05T20:53:17.135878+01:00] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"main","authenticator":"App\\Security\\LoginAuthenticator"} []
[2021-02-05T20:53:17.135934+01:00] security.DEBUG: Guard authenticator does not support the request. {"firewall_key":"main","authenticator":"App\\Security\\LoginAuthenticator"} []
[2021-02-05T20:53:17.151973+01:00] request.CRITICAL: Uncaught PHP Exception Twig\Error\LoaderError: "Unable to find template "login.html.twig" (looked into: C:\Users\Austin\Desktop\G3Excercise/templates, C:\Users\Austin\Desktop\G3Excercise\vendor\symfony\twig-bridge/Resources/views/Form)." at C:\Users\Austin\Desktop\G3Excercise\vendor\twig\twig\src\Loader\FilesystemLoader.php line 227 {"exception":"[object] (Twig\\Error\\LoaderError(code: 0): Unable to find template \"login.html.twig\" (looked into: C:\\Users\\Austin\\Desktop\\G3Excercise/templates, C:\\Users\\Austin\\Desktop\\G3Excercise\\vendor\\symfony\\twig-bridge/Resources/views/Form). at C:\\Users\\Austin\\Desktop\\G3Excercise\\vendor\\twig\\twig\\src\\Loader\\FilesystemLoader.php:227)"} []
[2021-02-05T20:53:17.280803+01:00] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2021-02-05T20:53:17.753378+01:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"e0241d"},"request_uri":"http://localhost:8000/_wdt/e0241d","method":"GET"} []
[2021-02-05T20:53:20.901289+01:00] request.INFO: Matched route "app_login". {"route":"app_login","route_parameters":{"_route":"app_login","_controller":"App\\Controller\\AuthController::login"},"request_uri":"http://localhost:8000/login","method":"GET"} []
[2021-02-05T20:53:20.923443+01:00] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"main","authenticators":1} []
[2021-02-05T20:53:20.923513+01:00] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"main","authenticator":"App\\Security\\LoginAuthenticator"} []
[2021-02-05T20:53:20.923557+01:00] security.DEBUG: Guard authenticator does not support the request. {"firewall_key":"main","authenticator":"App\\Security\\LoginAuthenticator"} []
[2021-02-05T20:53:21.032269+01:00] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2021-02-05T20:53:21.492816+01:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"242c3e"},"request_uri":"http://localhost:8000/_wdt/242c3e","method":"GET"} []
[2021-02-05T20:57:21.256635+01:00] request.INFO: Matched route "app_login". {"route":"app_login","route_parameters":{"_route":"app_login","_controller":"App\\Controller\\AuthController::login"},"request_uri":"http://localhost:8000/login","method":"POST"} []
[2021-02-05T20:57:21.284573+01:00] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"main","authenticators":1} []
[2021-02-05T20:57:21.284644+01:00] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"main","authenticator":"App\\Security\\LoginAuthenticator"} []
[2021-02-05T20:57:21.284695+01:00] security.DEBUG: Calling getCredentials() on guard authenticator. {"firewall_key":"main","authenticator":"App\\Security\\LoginAuthenticator"} []
[2021-02-05T20:57:21.285909+01:00] security.DEBUG: Passing guard token information to the GuardAuthenticationProvider {"firewall_key":"main","authenticator":"App\\Security\\LoginAuthenticator"} []
[2021-02-05T20:57:21.356547+01:00] request.CRITICAL: Uncaught PHP Exception RuntimeException: "The "App\Entity\User" entity has a repositoryClass set to "App\Repository\UserRepository", but this is not a valid class. Check your class naming. If this is meant to be a service id, make sure this service exists and is tagged with "doctrine.repository_service"." at C:\Users\Austin\Desktop\G3Excercise\vendor\doctrine\doctrine-bundle\Repository\ContainerRepositoryFactory.php line 59 {"exception":"[object] (RuntimeException(code: 0): The \"App\\Entity\\User\" entity has a repositoryClass set to \"App\\Repository\\UserRepository\", but this is not a valid class. Check your class naming. If this is meant to be a service id, make sure this service exists and is tagged with \"doctrine.repository_service\". at C:\\Users\\Austin\\Desktop\\G3Excercise\\vendor\\doctrine\\doctrine-bundle\\Repository\\ContainerRepositoryFactory.php:59)"} []
[2021-02-05T20:57:21.946890+01:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"b4a0de"},"request_uri":"http://localhost:8000/_wdt/b4a0de","method":"GET"} []
[2021-02-05T20:59:47.859714+01:00] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Config\Exception\LoaderLoadException: "[Semantical Error] The annotation "@Route" in method App\Controller\DefaultController::index() was never imported. Did you maybe forget to add a "use" statement for this annotation? in C:\Users\Austin\Desktop\G3Excercise\config/routes\../../src/Controller/ (which is being imported from "C:\Users\Austin\Desktop\G3Excercise\config/routes/annotations.yaml"). Make sure annotations are installed and enabled." at C:\Users\Austin\Desktop\G3Excercise\vendor\symfony\config\Loader\FileLoader.php line 173 {"exception":"[object] (Symfony\\Component\\Config\\Exception\\LoaderLoadException(code: 0): [Semantical Error] The annotation \"@Route\" in method App\\Controller\\DefaultController::index() was never imported. Did you maybe forget to add a \"use\" statement for this annotation? in C:\\Users\\Austin\\Desktop\\G3Excercise\\config/routes\\../../src/Controller/ (which is being imported from \"C:\\Users\\Austin\\Desktop\\G3Excercise\\config/routes/annotations.yaml\"). Make sure annotations are installed and enabled. at C:\\Users\\Austin\\Desktop\\G3Excercise\\vendor\\symfony\\config\\Loader\\FileLoader.php:173)\n[previous exception] [object] (Doctrine\\Common\\Annotations\\AnnotationException(code: 0): [Semantical Error] The annotation \"@Route\" in method App\\Controller\\DefaultController::index() was never imported. Did you maybe forget to add a \"use\" statement for this annotation? at C:\\Users\\Austin\\Desktop\\G3Excercise\\vendor\\doctrine\\annotations\\lib\\Doctrine\\Common\\Annotations\\AnnotationException.php:39)"} []
[2021-02-05T21:00:24.785482+01:00] request.INFO: Matched route "app_homepage". {"route":"app_homepage","route_parameters":{"_route":"app_homepage","_controller":"App\\Controller\\DefaultController::index"},"request_uri":"http://localhost:8000/","method":"GET"} []
[2021-02-05T21:00:24.812019+01:00] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"main","authenticators":1} []
[2021-02-05T21:00:24.812087+01:00] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"main","authenticator":"App\\Security\\LoginAuthenticator"} []
[2021-02-05T21:00:24.812128+01:00] security.DEBUG: Guard authenticator does not support the request. {"firewall_key":"main","authenticator":"App\\Security\\LoginAuthenticator"} []
[2021-02-05T21:00:24.833206+01:00] request.CRITICAL: Uncaught PHP Exception Twig\Error\LoaderError: "Unable to find template "login.html.twig" (looked into: C:\Users\Austin\Desktop\G3Excercise/templates, C:\Users\Austin\Desktop\G3Excercise\vendor\symfony\twig-bridge/Resources/views/Form)." at C:\Users\Austin\Desktop\G3Excercise\vendor\twig\twig\src\Loader\FilesystemLoader.php line 227 {"exception":"[object] (Twig\\Error\\LoaderError(code: 0): Unable to find template \"login.html.twig\" (looked into: C:\\Users\\Austin\\Desktop\\G3Excercise/templates, C:\\Users\\Austin\\Desktop\\G3Excercise\\vendor\\symfony\\twig-bridge/Resources/views/Form). at C:\\Users\\Austin\\Desktop\\G3Excercise\\vendor\\twig\\twig\\src\\Loader\\FilesystemLoader.php:227)"} []
[2021-02-05T21:00:24.929789+01:00] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2021-02-05T21:00:25.469901+01:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"509a32"},"request_uri":"http://localhost:8000/_wdt/509a32","method":"GET"} []
[2021-02-05T21:00:33.712613+01:00] request.INFO: Matched route "app_homepage". {"route":"app_homepage","route_parameters":{"_route":"app_homepage","_controller":"App\\Controller\\DefaultController::index"},"request_uri":"http://localhost:8000/","method":"GET"} []
[2021-02-05T21:00:33.742069+01:00] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"main","authenticators":1} []
[2021-02-05T21:00:33.742167+01:00] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"main","authenticator":"App\\Security\\LoginAuthenticator"} []
[2021-02-05T21:00:33.742219+01:00] security.DEBUG: Guard authenticator does not support the request. {"firewall_key":"main","authenticator":"App\\Security\\LoginAuthenticator"} []
[2021-02-05T21:00:33.772193+01:00] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2021-02-05T21:00:34.273493+01:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"ae01b5"},"request_uri":"http://localhost:8000/_wdt/ae01b5","method":"GET"} []
[2021-02-05T21:00:35.455127+01:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /favicon.ico" (from "http://localhost:8000/")" at C:\Users\Austin\Desktop\G3Excercise\vendor\symfony\http-kernel\EventListener\RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /favicon.ico\" (from \"http://localhost:8000/\") at C:\\Users\\Austin\\Desktop\\G3Excercise\\vendor\\symfony\\http-kernel\\EventListener\\RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico/\". at C:\\Users\\Austin\\Desktop\\G3Excercise\\vendor\\symfony\\routing\\Matcher\\Dumper\\CompiledUrlMatcherTrait.php:70)"} []
